add

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,31 +1,30 @@
 #!/usr/bin/env bash
-# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
-# The name of the custom HTTP header must be X-Served-By
-# The value of the custom HTTP header must be the hostname of the server Nginx is running on
-sudo apt-get update
-sudo apt-get -y install nginx
 
-# configure firewall to allow request through port 80
-sudo ufw allow 'Nginx HTTP'
+# Specify the path to your default Nginx configuration file
+nginx_conf="/etc/nginx/sites-enabled/default"
 
-sudo mkdir -p /var/www/html
+# Define the header to be added
+header_line="    add_header X-Served-By \$hostname;"
 
-# change permissions to allow us to easily create files in this directory
-sudo chmod -R 755 /var/www
+# Check if the configuration file exists
+if [ -f "$nginx_conf" ]; then
+    # Append the header line to the server block
+    sed -i "/^server {/a $header_line" "$nginx_conf"
+    
+    # Test the Nginx configuration
+    nginx -t
 
-#  create the index page
-echo 'Hello World!' |sudo tee  /var/www/html/index.html
+    # If the configuration test is successful, restart Nginx
+    if [ $? -eq 0 ]; then
+        systemctl restart nginx
+        echo "Header added successfully. Nginx restarted."
+    else
+        echo "Error: Nginx configuration test failed. Please check your configuration."
+    fi
+else
+    echo "Error: Nginx configuration file not found at $nginx_conf."
+fi
 
-# create a webpage for error 404
-echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
-
-# code to configure redirect for a single page(/redirect_me) and add header to display hostname
-string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
-sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
-
-# code to configure redirect for 404 error page
-string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
-sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default
 
 # restart the web server after updating the settings
 sudo service nginx restart
